In [1]:
import numpy as np
import pandas as pd

In [12]:
"""
Podemos indentificar se há ou nao headers no CSV  
com o argumento 'header'
"""
df = pd.read_csv('mushrooms.csv')
df.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [20]:
"""
O csv abaixo precisou de um encoding diferente do utf-8 para ser buildado como 
DataFrame. Para descobrir o encoding, abra um editor de texto e veja.
"""

df2 = pd.read_table('TA_PRECOS_MEDICAMENTOS.csv',delimiter="|",encoding='Windows 1252')
df2.head()

,NU_CNPJ,NO_RAZAO_SOCIAL,NU_REGISTRO,CO_GGREM,CO_EAN,NO_PRODUTO,DS_APRESENTACAO,DS_CAS,DS_SUBSTANCIA,TP_PRODUTO,TP_LCCT,ST_REST_HOSP,ST_CAP,ST_CONFAZ87,NU_PF0_INTEIRO,NU_PF18_INTEIRO
0,60726692000181,MARJAN INDÚSTRIA E COMÉRCIO LTDA,1015501950021,5.248018e+14,7896226102634,OSTENAN,10 MG COMP REV CX COM 30,121268-17-5,ALENDRONATO DE SÓDIO TRI-HIDRATADO,4.0,N,N,N,N,NaN,76.0
1,60726692000181,MARJAN INDÚSTRIA E COMÉRCIO LTDA,1015501950072,5.248018e+14,7896226102627,OSTENAN,10 MG COMP REV CX COM 15,121268-17-5,ALENDRONATO DE SÓDIO TRI-HIDRATADO,4.0,N,N,N,N,NaN,38.0
2,4038750000103,LIBRA COMERCIO DE PRODUTOS FARMACEUTICOS LTDA,1206900220020,5.238038e+14,7730711011233,TEICOPLANINA,400 MG PÓ LIOFILIZADO SOL INJ CX C/ 1 FR/AMP X...,99999-99-9,NC/NI,1.0,I,N,N,N,0.0,296.0
3,60726692000181,MARJAN INDÚSTRIA E COMÉRCIO LTDA,1015500410028,5.248001e+14,7896226100449,AMBROTEN,XPE ADU FR COM 100ML,18683-91-5,ambroxol,4.0,N,N,N,N,0.0,13.0
4,4038750000103,LIBRA COMERCIO DE PRODUTOS FARMACEUTICOS LTDA,1206900260022,5.238033e+14,7730711011493,OXALIPLATINA,50 MG PÓ LIOFILIZADO FR/AMP X 500 MG,99999-99-9,NC/NI,1.0,I,N,N,N,0.0,1187.0